name: 🐛 Laporan Bug (Bug Report)
description: Laporkan masalah atau error teknis pada antarmuka web, API, atau skrip psikometri.
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: Terima kasih telah melaporkan bug di StatsLab! Mohon isi detail di bawah ini agar kami dapat memverifikasi (*Tabayyun*).
  - type: textarea
    id: description
    attributes:
      label: Deskripsi Bug
      description: Jelaskan apa yang terjadi dan perilaku yang seharusnya muncul.
      placeholder: Saat membuka grafik Zakat di halaman summary, terjadi crash...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Langkah-Langkah Reproduksi
      description: Urutan langkah untuk memicu bug tersebut.
      placeholder: |
        1. Buka halaman '/dashboard'
        2. Klik sakelar 'Pilar Amanah'
        3. Lihat komponen grafik
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Peramban / Lingkungan
      placeholder: Chrome 125, macOS Sonoma, Next.js 15
    validations:
      required: false
