name: Latest Global Mathematics Education Research

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-research:
    name: Update README with latest global math education research
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull Latest Academic Feeds (OJS, DSpace, InfoMath)
        uses: gautamkrishnar/blog-post-workflow@v1
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: "0"
        with:
          comment_tag_name: GLOBAL_RESEARCH_LIST
          max_post_count: 5
          feed_list: "https://jurnal.staialbahjah.ac.id/index.php/abjme/gateway/plugin/WebFeedGatewayPlugin/rss2,https://j-cup.org/index.php/cendekia/gateway/plugin/WebFeedGatewayPlugin/rss2,https://www.kalamatika.matematika-uhamka.com/index.php/kmk/gateway/plugin/WebFeedGatewayPlugin/rss2,https://repository.uisu.ac.id/feed/rss_2.0/123456789/47"
