name: GitHub Metrics & Repository Pulse

on:
  schedule:
    - cron: '0 0 * * 1' # Berjalan otomatis setiap hari Senin
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics SVG
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: zaditprodakwah
          repo: statslab
          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
