name: Update Contributors in README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1' # Automatis berjalan setiap hari Senin
  workflow_dispatch:

permissions:
  contents: write

jobs:
  contrib-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update Contributors Image & List
        uses: contrib-rocks/action@v1.0.1
        with:
          repo: zaditprodakwah/statslab
          target: README.md
          key: CONTRIBUTORS
          max: 100

      - name: Commit & Push Changes
        uses: endbug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'chore(auto): update contributors list in README.md [skip ci]'
          add: 'README.md'
