name: Update Contributors in README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1' # Automatis berjalan setiap hari Senin
  workflow_dispatch:

permissions:
  contents: write

jobs:
  contrib-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update Contributors List
        uses: stefanweck/action-contributors@v3
        with:
          MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
